version: '3'

services:

  ruby:
    container_name: ruby
    image: rails
    command: rails s # ATENÇÃO: isso substitui o comando cmd do dockerfile, so use nao tiver dockerfile.
    restart: always # reinicia sempre que cair ##### unless-stopped - reinicia sempre que cair, mas nao quando voce pora
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # " porta de fora : porta de dentro "
    volumes:
      - .:/app
      - gems:/usr/local/bundle # facilita na hora do bundle install
    working_dir: /app # comeca o container na pasta app
    environment:
      - APP_NAME: "nome da aplicacao"
    stdin_open: true # mantém a entrada padrao aberta no terminal aberto, permitindo a entrada interativa.
    tty: true # aloca um terminal pseudo-TTY.
    depends_on: # so sobe se o outro subir
      - postgres  

volumes:
  gems:
